var annotated_dup =
[
    [ "MMG3D_PROctree", "structMMG3D__PROctree.html", "structMMG3D__PROctree" ],
    [ "MMG3D_PROctree_s", "structMMG3D__PROctree__s.html", "structMMG3D__PROctree__s" ],
    [ "MMG5_Bezier", "structMMG5__Bezier.html", "structMMG5__Bezier" ],
    [ "MMG5_dNode", "structMMG5__dNode.html", null ],
    [ "MMG5_dNode_s", "structMMG5__dNode__s.html", "structMMG5__dNode__s" ],
    [ "MMG5_Edge", "structMMG5__Edge.html", "structMMG5__Edge" ],
    [ "MMG5_Hash", "structMMG5__Hash.html", "structMMG5__Hash" ],
    [ "MMG5_hedge", "structMMG5__hedge.html", "structMMG5__hedge" ],
    [ "MMG5_hgeom", "structMMG5__hgeom.html", "structMMG5__hgeom" ],
    [ "MMG5_HGeom", "structMMG5__HGeom.html", "structMMG5__HGeom" ],
    [ "MMG5_Info", "structMMG5__Info.html", "structMMG5__Info" ],
    [ "MMG5_iNode", "structMMG5__iNode.html", null ],
    [ "MMG5_iNode_s", "structMMG5__iNode__s.html", "structMMG5__iNode__s" ],
    [ "MMG5_Mat", "structMMG5__Mat.html", "structMMG5__Mat" ],
    [ "MMG5_Mesh", "structMMG5__Mesh.html", "structMMG5__Mesh" ],
    [ "MMG5_Par", "structMMG5__Par.html", "structMMG5__Par" ],
    [ "MMG5_Point", "structMMG5__Point.html", "structMMG5__Point" ],
    [ "MMG5_Prism", "structMMG5__Prism.html", "structMMG5__Prism" ],
    [ "MMG5_Quad", "structMMG5__Quad.html", "structMMG5__Quad" ],
    [ "MMG5_Sol", "structMMG5__Sol.html", "structMMG5__Sol" ],
    [ "MMG5_sol", "structMMG5__sol.html", null ],
    [ "MMG5_Tetra", "structMMG5__Tetra.html", "structMMG5__Tetra" ],
    [ "MMG5_Tria", "structMMG5__Tria.html", "structMMG5__Tria" ],
    [ "MMG5_xPoint", "structMMG5__xPoint.html", "structMMG5__xPoint" ],
    [ "MMG5_xPrism", "structMMG5__xPrism.html", "structMMG5__xPrism" ],
    [ "MMG5_xTetra", "structMMG5__xTetra.html", "structMMG5__xTetra" ],
    [ "mytime", "structmytime.html", "structmytime" ]
];